name: geo_tasker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_map: ^8.2.2
  flutter_map_marker_popup: ^8.1.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.12
  firebase_core: ^3.7.0
  image_picker: ^1.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  uuid: ^4.5.1
  #speech_to_text: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
